# Generated by Django 4.1.7 on 2023-02-20 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iha',
            name='flight_time',
            field=models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Uçuş Süresi'),
        ),
    ]
