# Generated by Django 4.1.7 on 2023-02-21 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_alter_iha_flight_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iha',
            name='weight',
            field=models.DecimalField(decimal_places=0, max_digits=8, verbose_name='Ağırlık'),
        ),
    ]
