# Generated by Django 4.1.7 on 2023-02-22 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_alter_iha_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iha',
            name='flight_time',
            field=models.DecimalField(decimal_places=1, max_digits=12, verbose_name='Uçuş Süresi'),
        ),
        migrations.AlterField(
            model_name='iha',
            name='weight',
            field=models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Ağırlık'),
        ),
    ]
